ADMIN_PREFIX = "admin:"
ADMIN_NEW_PATIENT = "admin:new_patient"
ADMIN_ASSIGN = "admin:assign"
ADMIN_RESULTS = "admin:results"
ADMIN_RESULTS_SEARCH = "admin:results_search"
ADMIN_RESULT_PREFIX = "admin:result:"
ADMIN_BACK = "admin:back"
ADMIN_ENTER_PATIENT_CODE = "admin:patient_code"
ADMIN_PATIENT_PAGE_PREFIX = "admin:patient_page:"
ADMIN_PATIENT_PREFIX = "admin:patient:"
ADMIN_QUESTIONNAIRE_PREFIX = "admin:questionnaire:"

PATIENT_START_TEST = "patient:start_test"
ANSWER_PREFIX = "answer:"
